### ISSUE TITLE
'React/RCTBridgeModule.h' file not found

### ISSUE THREAD

**Issue by malekhassani** [frostney/react-native-create-library#46]
hey guys, I try to create a React Native library with "react-native-create-library". But when I open my iOS library I can't import the RCTBridgeModule.h.
thanks for your answers.

**Comment by viniciuspalma** [comment]
I have the same problem, I think React must be a dependency of the lib.

**Comment by viniciuspalma** [comment]
I found the PR that fixes this problem, #44

@malekhassani We must update the library and run again, or just make the same changes that have on this PR ;)

**Comment by malekhassani** [comment]
thank you @viniciuspalma, I solved the problem by adding the React.xcodeproj to my lib

**Comment by ademcan** [comment]
I have the same issue with the master branch, although this should have been fixed with the mentioned PR. I just create a new FancyLibrary, cd to the folder, run npm install and open the ios/xworkspace but I have the same issue mentioned in here.
Did you guys managed to solve it? I am using Xcode 10 on High Sierra.
Thank you

**Comment by maicki** [comment]
It's not possible to build the library within the Xcode project. You should link it into a project and develop within there.

**Comment by ademcan** [comment]
Ok, I see, it makes sense. I indeed managed to use it into a project, but thought as a first step to build it alone... thank you for your help @maicki

**Comment by eshiett1995** [comment]
> It's not possible to build the library within the Xcode project. You should link it into a project and develop within there.

1. What do you mean by it is not possible to build the library within the xcode project ?
2. How do you link it into a project and develop it there ?  because following this [article](https://ademcan.net/blog/2018/11/09/how-to-create-a-react-native-bridge-library-for-ios/), everything was done within the xcode project

**Comment by eshiett1995** [comment]
> #44

@viniciuspalma  How am I going to update the library, I am a bit confused. is it like this:

1. npm install -g react-native-create-library

2.react-native-create-library -—platforms ios,android NativeToastLibrary

3. cd NativeToastLibrary

4. npm install

because I tried the above step and   React/RCTBridgeModule.h' file  is still not found
